# -*- coding: utf-8 -*-
"""source.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBYzpftlQeCsP66-vkJTQ4UAQ2kiqFj9
"""

import torch

if torch.cuda.is_available():
    print("GPU is available!")
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("Number of GPUs:", torch.cuda.device_count())
else:
    print("GPU is NOT available.")

"""## Import Libraries"""

import re
import os
import string
import numpy as np
import pandas as pd
import seaborn as sns
from tqdm import tqdm

import matplotlib.pyplot as plt
import plotly.graph_objects as go

import pickle

from textwrap import wrap

import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import Sequence
from tensorflow.keras.utils import to_categorical, plot_model
from tensorflow.keras.models import Sequential, Model, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D, Activation, Dropout, Flatten, Dense, Input, Layer
from tensorflow.keras.layers import Embedding, LSTM, add, Concatenate, Reshape, concatenate, Bidirectional
from tensorflow.keras.applications import DenseNet201
from tensorflow.keras.callbacks import LearningRateScheduler

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from sklearn.model_selection import train_test_split

from tqdm import tqdm_notebook
from PIL import Image
from collections import Counter

"""## Connect to Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""# Train model with Flickr8k Dataset

## Load Dataset
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("adityajn105/flickr8k")

print("Path to dataset files:", path)

flickr8k = '/kaggle/input/flickr8k/'
images_path = flickr8k + 'Images/'
captions_path = flickr8k + 'captions.txt'

data = pd.read_csv(captions_path)
print(data.shape)
data.head()

def read_image(path, img_size=224):
  img = load_img(path, color_mode='rgb', target_size=(img_size, img_size))
  img = img_to_array(img)
  img = img / 255.
  return img

def display_images(temp_df, img_num=10):
  temp_df = temp_df.reset_index(drop=True)
  plt.figure(figsize = (20, 20))
  n = 0
  for i in range(img_num):
    n += 1
    plt.subplot(5, 5, n)
    plt.subplots_adjust(hspace=0.7, wspace=0.3)

    img = read_image(images_path + temp_df['image'][i])
    plt.imshow(img)
    plt.title("\n".join(wrap(temp_df['caption'][i], 20)))
    plt.axis('off')

display_images(data.sample(10))

"""## Preprocess captions"""

def text_preprocessing(data):
    data['cleaned_caption'] = data['caption'].copy()
    data['cleaned_caption'] = data['cleaned_caption'].apply(lambda x: x.lower())
    data['cleaned_caption'] = data['cleaned_caption'].apply(lambda x: re.sub(f'[{re.escape(string.punctuation)}]', '', x))
    data['cleaned_caption'] = data['cleaned_caption'].apply(lambda x: re.sub(r'[^a-z\s]', '', x))
    data['cleaned_caption'] = data['cleaned_caption'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())
    data['cleaned_caption'] = data['cleaned_caption'].apply(lambda x: " ".join([word for word in x.split() if len(word) > 1 or word in ['a']]))
    data['cleaned_caption'] = "<bos> " + data['cleaned_caption'] + " <eos>"
    return data

data = text_preprocessing(data)
captions = data['cleaned_caption'].tolist()
captions[:7]

"""## Build Tokenizer"""

tokenizer = Tokenizer()
tokenizer.fit_on_texts(captions)
vocab_size = len(tokenizer.word_index) + 1
max_length = max(len(caption.split()) for caption in captions)

print('Vocabulary Size: %d' % vocab_size)
print('Description Length: %d' % max_length)

# with open('/content/drive/MyDrive/CV/NIC/tokenizer.pkl', 'wb') as handle:
#     pickle.dump(tokenizer, handle)

print(captions[1])
tokenizer.texts_to_sequences([captions[1]])[0]

"""## Split Dataset

**20% Train - 10% Val - 10% Test**
"""

images = data['image'].unique().tolist()
num_images = len(images)
print(f"Number of images: {num_images}")

train, val = train_test_split(images, test_size=0.2, random_state=42)
test, val = train_test_split(val, test_size=0.5, random_state=42)
print(f"\nNumber of train images: {len(train)}")
print(f"Number of validation images: {len(val)}")
print(f"Number of test images: {len(test)}")

train_df = data[data['image'].isin(train)].copy()
val_df = data[data['image'].isin(val)].copy()
test_df = data[data['image'].isin(test)].copy()
print(f"\nTrain Captions: {len(train_df)}")
print(f"Validation Captions: {len(val_df)}")
print(f"Test Captions: {len(test_df)}")

train_df.reset_index(inplace=True, drop=True)
val_df.reset_index(inplace=True, drop=True)
test_df.reset_index(inplace=True, drop=True)

"""## Load Pretrained CNN

**Use DenseNet201 model to extract image features**
"""

model = DenseNet201()
fe = Model(inputs=model.inputs, outputs=model.layers[-2].output)
img_size = 224

flickr8k_features = {}
for image in tqdm(images):
  img = load_img(images_path + image, target_size=(img_size, img_size))
  img = img_to_array(img)
  img = img / 255.
  img = np.expand_dims(img, axis=0)
  feature = fe.predict(img, verbose=0)
  flickr8k_features[image] = feature

# features_path = '/content/drive/MyDrive/Dataset/NIC/flickr8k_features.pkl'

# with open(features_path, 'wb') as f:
#     pickle.dump(flickr8k_features, f)
# print(f"Features saved to {features_path}")

# path = '/content/drive/MyDrive/Dataset/NIC/flickr8k_features.pkl'
# with open(path, 'rb') as f:
#   flickr8k_features = pickle.load(f)

plt.imshow(load_img(images_path + data['image'][100]))
print(captions[100])
flickr8k_features[data['image'][100]]

"""## Building a custom generator function to generate input image features"""

batch_size = 64
X_col = 'image'
y_col = 'cleaned_caption'

class CustomDataGenerator(Sequence):
    def __init__(self, df, features, X_col=X_col, y_col=y_col, batch_size=batch_size, tokenizer=tokenizer, vocab_size=vocab_size, max_length=max_length, shuffle=True):
      self.df = df.copy()
      self.X_col = X_col
      self.y_col = y_col
      self.batch_size = batch_size
      self.tokenizer = tokenizer
      self.vocab_size = vocab_size
      self.max_length = max_length
      self.features = features
      self.shuffle = shuffle
      self.n = len(self.df)

    def on_epoch_end(self):
      if self.shuffle:
        self.df = self.df.sample(frac=1).reset_index(drop=True)

    def __len__(self):
      return self.n // self.batch_size

    def __getitem__(self, index):
      batch = self.df.iloc[index * self.batch_size:(index + 1) * self.batch_size, :]
      X1, X2, y = self.__get_data(batch)
      return (X1, X2), y

    def __get_data(self, batch):
      X1, X2, y = list(), list(), list()
      images_in_batch = batch[self.X_col].tolist()

      for image_id in images_in_batch:
        feature = self.features[image_id][0]
        captions = batch.loc[batch[self.X_col] == image_id, self.y_col].tolist()
        for caption in captions:
          seq = self.tokenizer.texts_to_sequences([caption])[0]
          for i in range(1, len(seq)):
            in_seq, out_seq = seq[:i], seq[i]
            in_seq = pad_sequences([in_seq], maxlen=self.max_length)[0]
            out_seq = to_categorical([out_seq], num_classes=self.vocab_size)[0]
            X1.append(feature)
            X2.append(in_seq)
            y.append(out_seq)

      X1, X2, y = np.array(X1), np.array(X2), np.array(y)
      return X1, X2, y

"""## Build Model's Architecture

### Define building function
"""

def build_model(vocab_size=vocab_size, max_length=max_length):
  input1 = Input(shape=(1920, ))
  img_features = Dense(256, activation='relu')(input1)
  img_features_reshaped = Reshape((1, 256), input_shape=(256,))(img_features)

  input2 = Input(shape=(max_length, ))
  sentence_features = Embedding(vocab_size, 256, mask_zero=False)(input2)

  merged = concatenate([img_features_reshaped, sentence_features], axis=1)
  sentence_features = LSTM(256)(merged)

  x = Dropout(0.5)(sentence_features)
  x = add([x, img_features])
  x = Dense(128, activation='relu')(x)
  x = Dropout(0.5)(x)
  output = Dense(vocab_size, activation='softmax')(x)

  caption_model = Model(inputs=[input1, input2], outputs=output)
  caption_model.compile(loss='categorical_crossentropy', optimizer='adam')

  return caption_model

caption_model = build_model()
caption_model.summary()

train_generator = CustomDataGenerator(df=train_df, features=flickr8k_features)
val_generator = CustomDataGenerator(df=val_df, features=flickr8k_features)

model_name = 'caption_generator.keras'
epochs = 30
checkpoint = ModelCheckpoint(model_name, monitor="val_loss", mode="min", save_best_only = True, verbose=1)
early_stopping = EarlyStopping(monitor='val_loss', min_delta = 0, patience = 5, verbose = 1, restore_best_weights=True)
learning_rate_reduction = ReduceLROnPlateau(monitor='val_loss', patience=3, verbose=1, factor=0.2, min_lr=1e-4)

"""### Training"""

history = caption_model.fit(train_generator, epochs=epochs,
                            validation_data=val_generator,
                            callbacks=[checkpoint, early_stopping, learning_rate_reduction])

# caption_model.save('/content/drive/MyDrive/CV/NIC/caption_model.keras')

"""## Loss curve"""

plt.figure(figsize=(20,8))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

"""## Inference"""

def idx_to_word(idx, tokenizer=tokenizer):
    for word, i in tokenizer.word_index.items():
        if i == idx:
            return word
    return None

def preprocess_img(img_path, img_size=224):
  img = load_img(img_path, target_size=(img_size, img_size))
  img = img_to_array(img)
  img = img / 255.
  img = np.expand_dims(img, axis=0)
  return img

def get_image_feature(img_path):
  img = preprocess_img(img_path)
  feature = fe.predict(img, verbose=0)
  return feature

def predict_caption(model, image, features=None, tokenizer=tokenizer, max_length=max_length):
    in_text = 'bos'

    if features:
      feature = features[image]
    else:
      feature = get_image_feature(image)

    for i in range(max_length):
        # encode input sequence
        sequence = tokenizer.texts_to_sequences([in_text])[0]
        # pad the sequence
        sequence = pad_sequences([sequence], max_length)
        # predict next word
        y_pred = model.predict([feature, sequence], verbose=0)
        # get index of the word with high probability
        y_pred = np.argmax(y_pred)
        # convert index to word
        word = idx_to_word(y_pred, tokenizer)

        if word is None:
            break

        in_text += " " + word

        if word == 'eos':
            break
    return in_text.replace('bos ', '').replace(' eos', '').strip()

def predict_and_display(model, test_df, features, images_path=images_path, tokenizer=tokenizer, max_length=max_length, num_samples=15):
    test_df = test_df.sample(num_samples)
    test_df.reset_index(inplace=True, drop=True)
    plt.figure(figsize=(20, 20))
    n = 0
    for i in range(num_samples):
        n += 1
        plt.subplot(5, 5, n)
        plt.subplots_adjust(hspace=0.7, wspace=0.3)

        image_filename = test_df['image'][i]
        image_path = images_path + image_filename

        predicted_caption = predict_caption(model=model, image=image_filename, tokenizer=tokenizer, features=features, max_length=max_length)

        img = read_image(image_path)
        plt.imshow(img)
        plt.title("\n".join(wrap(f"{predicted_caption}", 20)))
        plt.axis('off')

    plt.show()

predict_and_display(model=caption_model, test_df=test_df, num_samples=10, features=flickr8k_features)

"""## Evaluate"""

def _clean_caption_for_bleu_evaluation(caption_string):
    return [
        word for word in caption_string.lower().split()
        if word not in ['<bos>', '<eos>', '<BOS>', '<EOS>', 'bos', 'eos']
    ]

def evaluate_bleu_score(model, df, features, tokenizer=tokenizer, max_length=max_length, num_samples=10):
    image_to_cleaned_refs = {}
    unique_images = df['image'].unique()

    for img_filename in unique_images:
        raw_captions = df.loc[df['image'] == img_filename, 'cleaned_caption'].tolist()
        cleaned_refs_for_image = []
        for cap_str in raw_captions:
            cleaned_words = _clean_caption_for_bleu_evaluation(cap_str)
            if cleaned_words:
                cleaned_refs_for_image.append(cleaned_words)
        if cleaned_refs_for_image:
            image_to_cleaned_refs[img_filename] = cleaned_refs_for_image

    sampled_image_ids = np.random.choice(list(image_to_cleaned_refs.keys()), min(num_samples, len(image_to_cleaned_refs)), replace=False)

    actual_corpora = []
    predicted_corpora = []

    smoothie = SmoothingFunction().method4

    for image_filename in tqdm(sampled_image_ids, desc="Generating captions"):
        actual_captions_for_image = image_to_cleaned_refs[image_filename]
        predicted_caption_str = predict_caption(model=model, image=image_filename, features=features)
        predicted_caption_words = predicted_caption_str.split()

        actual_corpora.append(actual_captions_for_image)
        predicted_corpora.append(predicted_caption_words)

    print('\nBLEU-1: %f' % corpus_bleu(actual_corpora, predicted_corpora, weights=(1.0, 0, 0, 0), smoothing_function=smoothie))
    print('BLEU-2: %f' % corpus_bleu(actual_corpora, predicted_corpora, weights=(0.5, 0.5, 0, 0), smoothing_function=smoothie))
    print('BLEU-3: %f' % corpus_bleu(actual_corpora, predicted_corpora, weights=(0.333, 0.333, 0.333, 0), smoothing_function=smoothie))
    print('BLEU-4: %f' % corpus_bleu(actual_corpora, predicted_corpora, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=smoothie))

"""**flickr8k**"""

evaluate_bleu_score(model=caption_model, df=test_df, num_samples=len(test_df), features=flickr8k_features)

"""## Test with images not in the dataset"""

test_img = "test1.jpg"
plt.imshow(load_img(test_img))
predict_caption(caption_model, test_img)

test_img = "test2.jpg"
plt.imshow(load_img(test_img))
predict_caption(caption_model, test_img)

"""# Fine-tunining model with Flickr30k Dataset

## Load dataset
"""

path = kagglehub.dataset_download("adityajn105/flickr30k")
print("Path to dataset files:", path)

flickr30K = '/kaggle/input/flickr30k/'
flickr30K_captions_path = flickr30K + 'captions.txt'
flickr30K_images_path = flickr30K + 'Images/'

df_30k = pd.read_csv(flickr30K_captions_path)
print(df_30k.shape)
df_30k.head()

"""## Check NaN Value"""

len(df_30k)/5., len(df_30k['image'].unique())

df_30k[df_30k['caption'].isnull()]

df_30k[df_30k['image'] == '2199200615.jpg']

plt.imshow(load_img(flickr30K_images_path + '2199200615.jpg'))

df_30k['caption'] = df_30k['caption'].fillna('A dog is running across a green lawn .')
df_30k.isnull().sum()

"""## Preprocess captions"""

df_30k = text_preprocessing(df_30k)

"""**Remove rows if tokens of caption > 37 because max_len of tokenizer = 37**"""

# count how many cleaned caption tokens > 37 (we will remove rows if tokens of caption > 37 because max_len of tokenizer = 37)

caption_lengths = df_30k['cleaned_caption'].apply(lambda x: len(x.split()))
count_greater_than_37 = (caption_lengths > 37).sum()
print(f"Number of cleaned caption tokens > 37: {count_greater_than_37}")

# find all rows X that have cleaned caption > 37, then delete X and even row has cleaned caption <= 37 but has the same column 'image' with row if X

# Find rows where 'cleaned_caption' length is > 37
rows_to_delete = df_30k[df_30k['cleaned_caption'].apply(lambda x: len(x.split())) > 37]

# Get the 'image' values from these rows
images_to_delete = rows_to_delete['image'].unique()

# Find rows where 'cleaned_caption' length is <= 37
rows_to_check = df_30k[df_30k['cleaned_caption'].apply(lambda x: len(x.split())) <= 37]

# Identify rows with 'cleaned_caption' <= 37 and 'image' matching any of the images from rows_to_delete
additional_rows_to_delete = rows_to_check[rows_to_check['image'].isin(images_to_delete)]

# Combine the indices of all rows to delete
indices_to_delete = pd.concat([rows_to_delete, additional_rows_to_delete]).index

# Drop the rows from the DataFrame
df_30k = df_30k.drop(indices_to_delete)

print(f"Number of rows deleted: {len(indices_to_delete)}")
print(f"Remaining rows: {len(df_30k)}")

len(df_30k) / 5., len(df_30k['image'].unique())

"""## Split dataset

**80% Train - 20% Val**
"""

images = df_30k['image'].unique().tolist()
num_images = len(images)
print(f"Number of images: {num_images}")

train, val = train_test_split(images, test_size=0.2, random_state=42)

print(f"\nNumber of train images: {len(train)}")
print(f"Number of validation images: {len(val)}")

train_df = df_30k[df_30k['image'].isin(train)].copy()
val_df = df_30k[df_30k['image'].isin(val)].copy()

print(f"\nTrain Captions: {len(train_df)}")
print(f"Validation Captions: {len(val_df)}")


train_df.reset_index(inplace=True, drop=True)
val_df.reset_index(inplace=True, drop=True)

len(train_df) / 5., len(train_df['image'].unique())

len(val_df) / 5., len(val_df['image'].unique())

"""## Load model (trained with Flickr8k)"""

model_name = 'caption_generator.keras'
epochs = 30
checkpoint = ModelCheckpoint(model_name, monitor="val_loss", mode="min", save_best_only = True, verbose=1)
early_stopping = EarlyStopping(monitor='val_loss', min_delta = 0, patience = 5, verbose = 1, restore_best_weights=True)
learning_rate_reduction = ReduceLROnPlateau(monitor='val_loss', patience=3, verbose=1, factor=0.2, min_lr=1e-5)

caption_model = load_model('/content/drive/MyDrive/CV/NIC/caption_generator.keras')
caption_model.summary()

"""**Extract image features**"""

flickr30k_features = {}
for image in tqdm(images):
  img = load_img(images_path + image, target_size=(img_size, img_size))
  img = img_to_array(img)
  img = img / 255.
  img = np.expand_dims(img, axis=0)
  feature = fe.predict(img, verbose=0)
  flickr30k_features[image] = feature

# with open('/content/drive/MyDrive/CV/NIC/flickr30k_features.pkl', 'wb') as f:
#     pickle.dump(flickr30k_features, f)
# print(f"Features saved to flickr30k_features.pkl")

# with open('/content/drive/MyDrive/CV/NIC/flickr30k_features.pkl', 'rb') as f:
#     flickr30k_features = pickle.load(f)

train_generator = CustomDataGenerator(df=train_df, features=flickr30k_features)
val_generator = CustomDataGenerator(df=val_df, features=flickr30k_features)

"""## Fine-tune model"""

history = caption_model.fit(train_generator, epochs=epochs,
                            validation_data=val_generator,
                            callbacks=[checkpoint, early_stopping, learning_rate_reduction])

"""## Loss curve"""

plt.figure(figsize=(20,8))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

# caption_model.save('/content/drive/MyDrive/CV/NIC/caption_model.keras')

# caption_model = load_model('/content/drive/MyDrive/CV/NIC/caption_model.keras')
# caption_model.summary()

"""## Evaluate"""

predict_and_display(model=caption_model, test_df=test_df, num_samples=10, features=flickr8k_features)

evaluate_bleu_score(model=caption_model, df=test_df, num_samples=len(test_df), features=flickr8k_features)

"""## Test with images not in the dataset"""

test_img = "test1.jpg"
plt.imshow(load_img(test_img))
predict_caption(caption_model, test_img)

test_img = "test2.jpg"
plt.imshow(load_img(test_img))
predict_caption(caption_model, test_img)

"""# Draw chart to compare BLEU scores

Flickr8k's model vs. Fine-tuned FLickr30k's model
"""

# Data
metrics = ['BLEU-1', 'BLEU-2', 'BLEU-3', 'BLEU-4']
flickr8k_scores = [0.569517, 0.380212, 0.242319, 0.151715]
flickr30k_finetune_scores = [0.605874, 0.415633, 0.272168, 0.176108]

x = np.arange(len(metrics))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))

# Plotting the bars
rects1 = ax.bar(x - width/2, flickr8k_scores, width, label='Trained on Flickr8k Only')
rects2 = ax.bar(x + width/2, flickr30k_finetune_scores, width, label='Flickr8k + Fine-tuned on Flickr30k')

# Adding labels, title, and legend
ax.set_ylabel('BLEU Score')
ax.set_title('Comparison of BLEU Scores Across Training Approaches')
ax.set_xticks(x)
ax.set_xticklabels(metrics)
ax.legend()
ax.grid(axis='y', linestyle='--', alpha=0.7)

# Function to add numerical values on top of the bars
def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate('%.3f' % height,
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)

plt.tight_layout()
plt.show()